### ISSUE TITLE
你好，请问如何将数据库持久化？

### ISSUE THREAD

**Issue by neroxps** [gilbert-yuan/gooderp_docker#1]
刚接触 gooderp，感觉环境搭建十分费时，想用docker，一搜发现这项目。

看了下阁下的 Dockerfile，请问系统的数据如何持久化？

**Comment by gilbert-yuan** [comment]
不好意思,持久化的方法 我也没有尝试过.这个镜像主要是用来做开发用的.(你可以参考别人做的odoo相关的持久化的方案,大同小异)

**Comment by neroxps** [comment]
明白，我参考下您做的 docker 来做一个持久化的 docker 吧~谢谢
